In [ ]:
import torch

torch_scalar = torch.tensor(3.14)
torch_vector = torch.tensor([1,2,3,4])
torch_matrix = torch.tensor([[1,2,],[3,4,],[5,6,],[7,8,]]) 
torch_tensor3d = torch.tensor([
 [
 [1, 2, 3],
 [4, 5, 6],
 ],
 [
 [7, 8, 9],
 [10,11,12],
 ],
 [
 [13,14,15],
 [16,17,18],
 ],
 [ [19,20,21],
 [22,23,24],
 ]
 ]) 

In [2]:
print(torch_scalar.shape)
print(torch_vector.shape)
print(torch_matrix.shape)
print(torch_tensor3d.shape) 

torch.Size([])
torch.Size([4])
torch.Size([4, 2])
torch.Size([4, 2, 3])


In [9]:
import numpy as np

x_np = np.random.random((4,4))
print(x_np)

x_pt = torch.tensor(x_np)
print(x_pt)


[[0.09440526 0.98722899 0.47119998 0.33136616]
 [0.58970351 0.83201426 0.21321663 0.36986292]
 [0.70681459 0.3027702  0.77108865 0.27714152]
 [0.36573735 0.83446999 0.89338181 0.96777684]]
tensor([[0.0944, 0.9872, 0.4712, 0.3314],
        [0.5897, 0.8320, 0.2132, 0.3699],
        [0.7068, 0.3028, 0.7711, 0.2771],
        [0.3657, 0.8345, 0.8934, 0.9678]], dtype=torch.float64)


Why numpy tensors are different from pytorch tensors ? Are their computing workflows different ?

In [11]:
print(x_np.dtype, x_pt.dtype)

#Lets force them to be 32-bit floats
x_np = np.asarray(x_np, dtype=np.float32)
x_pt = torch.tensor(x_np, dtype=torch.float32)
print(x_np.dtype, x_pt.dtype) 

float64 torch.float64
float32 torch.float32


Let's say we wanted to find every value in a tensor that was greater than 0.5. Both PyTorch and NumPy would allow us to use the standard logic operators to check for things like this.

In [12]:
b_np = (x_np > 0.5)
print(b_np)
print(b_np.dtype)

b_pt = (x_pt > 0.5)
print(b_pt)
print(b_pt.dtype)


[[False  True False False]
 [ True  True False False]
 [ True False  True False]
 [False  True  True  True]]
bool
tensor([[False,  True, False, False],
        [ True,  True, False, False],
        [ True, False,  True, False],
        [False,  True,  True,  True]])
torch.bool


In [16]:
print(np.sum(x_np))


torch.sum(x_pt)

9.008179


tensor(9.0082)

In [19]:
np.transpose(x_np) 

torch.transpose(x_pt,0,1)

tensor([[0.0944, 0.5897, 0.7068, 0.3657],
        [0.9872, 0.8320, 0.3028, 0.8345],
        [0.4712, 0.2132, 0.7711, 0.8934],
        [0.3314, 0.3699, 0.2771, 0.9678]])

What is a ranspose and to what does it serves ?