In [2]:
import torch

torch_scalar = torch.tensor(3.14)
torch_vector = torch.tensor([1,2,3,4])
torch_matrix = torch.tensor([[1,2,],[3,4,],[5,6,],[7,8,]]) 
torch_tensor3d = torch.tensor([
 [
 [1, 2, 3],
 [4, 5, 6],
 ],
 [
 [7, 8, 9],
 [10,11,12],
 ],
 [
 [13,14,15],
 [16,17,18],
 ],
 [ [19,20,21],
 [22,23,24],
 ]
 ]) 

In [3]:
print(torch_scalar.shape)
print(torch_vector.shape)
print(torch_matrix.shape)
print(torch_tensor3d.shape) 

torch.Size([])
torch.Size([4])
torch.Size([4, 2])
torch.Size([4, 2, 3])


In [4]:
import numpy as np

x_np = np.random.random((4,4))
print(x_np)

x_pt = torch.tensor(x_np)
print(x_pt)


[[0.42526797 0.97864026 0.7849301  0.22836818]
 [0.29588147 0.30661269 0.54704924 0.41499764]
 [0.70479876 0.91119634 0.75907667 0.65560338]
 [0.38863444 0.20459368 0.09782613 0.53072201]]
tensor([[0.4253, 0.9786, 0.7849, 0.2284],
        [0.2959, 0.3066, 0.5470, 0.4150],
        [0.7048, 0.9112, 0.7591, 0.6556],
        [0.3886, 0.2046, 0.0978, 0.5307]], dtype=torch.float64)


Why numpy tensors are different from pytorch tensors ? Are their computing workflows different ?

In [5]:
print(x_np.dtype, x_pt.dtype)

#Lets force them to be 32-bit floats
x_np = np.asarray(x_np, dtype=np.float32)
x_pt = torch.tensor(x_np, dtype=torch.float32)
print(x_np.dtype, x_pt.dtype) 

float64 torch.float64
float32 torch.float32


Let's say we wanted to find every value in a tensor that was greater than 0.5. Both PyTorch and NumPy would allow us to use the standard logic operators to check for things like this.

In [6]:
b_np = (x_np > 0.5)
print(b_np)
print(b_np.dtype)

b_pt = (x_pt > 0.5)
print(b_pt)
print(b_pt.dtype)


[[False  True  True False]
 [False False  True False]
 [ True  True  True  True]
 [False False False  True]]
bool
tensor([[False,  True,  True, False],
        [False, False,  True, False],
        [ True,  True,  True,  True],
        [False, False, False,  True]])
torch.bool


In [7]:
print(np.sum(x_np))


torch.sum(x_pt)

8.2342


tensor(8.2342)

In [8]:
np.transpose(x_np) 

torch.transpose(x_pt,0,1)

tensor([[0.4253, 0.2959, 0.7048, 0.3886],
        [0.9786, 0.3066, 0.9112, 0.2046],
        [0.7849, 0.5470, 0.7591, 0.0978],
        [0.2284, 0.4150, 0.6556, 0.5307]])

What is a ranspose and to what does it serves ?

In [10]:
import timeit
x = torch.rand(2**11,2**11)
time_cpu = timeit.timeit("x@x", globals=globals(), number=100)
print(time_cpu)

31.623031095999977


In [14]:
device = torch.device("cpu")
print(device)
x = x.to(device)
time_cpu = timeit.timeit("x@x", globals=globals(), number=100)
print(x)

cpu
tensor([[0.9939, 0.4511, 0.9180,  ..., 0.5196, 0.2975, 0.0992],
        [0.0606, 0.8562, 0.3645,  ..., 0.3846, 0.2514, 0.6621],
        [0.2962, 0.7762, 0.5770,  ..., 0.5796, 0.3639, 0.6935],
        ...,
        [0.5656, 0.9104, 0.0649,  ..., 0.5404, 0.0133, 0.8356],
        [0.1381, 0.2157, 0.0793,  ..., 0.8155, 0.0224, 0.4657],
        [0.8236, 0.2211, 0.4229,  ..., 0.9248, 0.1407, 0.7187]])
